# Generated by Django 2.2.1 on 2019-06-16 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_auto_20190617_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalexperience',
            name='first_day',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='professionalexperience',
            name='last_day',
            field=models.DateField(auto_now=True),
        ),
    ]
