# Generated by Django 2.2.1 on 2019-06-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20190617_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalexperience',
            name='job_description',
            field=models.TextField(),
        ),
    ]
