# Generated by Django 2.2.1 on 2019-06-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0011_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalexperience',
            name='month',
        ),
        migrations.AlterField(
            model_name='banner',
            name='banner',
            field=models.ImageField(upload_to='about/banner'),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='social_media',
            field=models.CharField(choices=[('fa-twitter', 'Twitter'), ('fa-facebook', 'Facebook'), ('fa-dribbble', 'Dribbble'), ('fa-flickr', 'Flickr'), ('fa-github', 'Github')], default='fa-twitter', max_length=100),
        ),
    ]
