# Generated by Django 2.2.1 on 2019-06-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0012_auto_20190623_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatidoitem',
            name='icon',
            field=models.CharField(default='fa-desktop', max_length=100),
        ),
    ]
