# Generated by Django 2.2.1 on 2019-06-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0013_whatidoitem_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatidoitem',
            name='icon',
            field=models.CharField(default='fa-', max_length=100),
        ),
    ]
