# Generated by Django 2.2.1 on 2019-06-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0016_skillitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='about.Portfolio'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(default=2, upload_to='about/portfolio'),
            preserve_default=False,
        ),
    ]
