# Generated by Django 2.2.1 on 2019-06-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0017_auto_20190624_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tag',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
