# Generated by Django 2.2.1 on 2019-06-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0018_portfolio_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='link',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
